### PR TITLE
cleaned up code for adding searchbar and savedlocation js files.

### PR DESCRIPTION
**Pull request by brand0n-y00n**
1.  added cors into server
2.  cleaned up searchLocation function so now frontend receives weather information from backend
3.  installed file-loader as devDependency

### CODE REVIEW

**Review by lennin6 — COMMENTED** [review]
wow.!!

**Review by alexyam0 — APPROVED** [review]
wow!!

**Review by lennin6 — APPROVED** [review]
OOOH!!!

**Comment by brand0n-y00n** [comment]
> wow.!!

Thanks!

**Pull request merged**
